### ISSUE TITLE
Backlog responds incorrectly for query windows

### ISSUE THREAD

**Issue by w0rp** [FruitieX/znc-backlog#10]
If you request a backlog for a user instead of a channel, the backlog will fire the messages from user FOO as coming from user FOO back at you, but your messages _to_ user FOO as if you were sending messages to yourself. So you'll see your replies in the backlog in a different window on most IRC clients.

Could you change the backlog so it sends messages for queries such that they all appear in the one window, with some text pre-pended so you can see who said what?

**Comment by walliski** [comment]
Was actually going to this issue myself. One could probably generate a fake nick, and send both parts conversations to a dummy window, or have it come to the *backlog one... But then you can't respond to the person directly in that window. Would of course make reading the backlog a lot easier.

Other alternative would be to simply not send your own messages, but then again you wont get any context what so ever. Maybe the *backlog solution would be the best.

**Comment by w0rp** [comment]
I think maybe it should send all of the messages as if they came from the user you're getting the backlog for, but prepend some text to each message to indicate which user they really came from. One complication there is that it would have to handle the maximum line length, but then it probably does that anyway for the timestamps.

**Comment by walliski** [comment]
Aaah, yeah, that could also of course be an alternative.. :+1:
